In [2]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn import datasets

In [3]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

In [4]:
model = SVC(kernel='linear')
model.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [9]:
from sklearn.grid_search import GridSearchCV

parameters = {'kernel':('linear', 'rbf', 'poly'), 
              'C':[0.1, 0.4, 0.5, 0.6, 1, 3, 10]}
clf = GridSearchCV(model, parameters, n_jobs=-1)
clf.fit(X,y)
clf.best_estimator_

SVC(C=0.6, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

simple example

In [11]:
from sklearn import svm

X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC()
clf.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [12]:
clf.predict([[2., 2.]])

array([1])

In [13]:
clf.predict([[-1., -1.]])

array([0])

In [14]:
clf.predict([[3., 3.]])

array([1])

In [15]:
clf.predict([[0.5, 0.5]])

array([1])

In [16]:
clf.predict([[0.5, 0.4]])

array([0])

In [19]:
#support vectors
clf.support_vectors_

array([[ 0.,  0.],
       [ 1.,  1.]])

In [20]:
#number of dupport vectors for each class
clf.n_support_

array([1, 1], dtype=int32)